"""Initial migration on new table

Revision ID: 16a1da46905a
Revises: 
Create Date: 2023-10-11 12:10:29.612344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16a1da46905a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_ibfk_1', type_='foreignkey')
        batch_op.drop_column('date')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.create_foreign_key('schedule_ibfk_1', 'user', ['user_id'], ['id'], onupdate='CASCADE')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('case_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='status_ibfk_2', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='status_ibfk_1', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
