"""with audit trail

Revision ID: 605bceefa250
Revises: 7139df155d47
Create Date: 2023-12-07 11:05:55.373121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '605bceefa250'
down_revision = '7139df155d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audittrail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', sa.String(length=10), nullable=True))
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('action_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audittrail_case_id'), ['case_id'], unique=False)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('case_no',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('case_title',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('case_complainant',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('address_complainant',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('contact_complainant',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('case_respondent',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('address_respondent',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('contact_respondent',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('barangay',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('note_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], onupdate='CASCADE')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_status_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_case_id'))
        batch_op.alter_column('remarks',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('note_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('barangay',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('contact_respondent',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('address_respondent',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('case_respondent',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('contact_complainant',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('address_complainant',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('case_complainant',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('case_title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('case_no',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('audittrail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audittrail_case_id'))
        batch_op.alter_column('action_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.drop_column('action_id')

    # ### end Alembic commands ###
