"""Initial migration

Revision ID: 640cfcdb7498
Revises: 
Create Date: 2025-04-25 11:27:51.473018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640cfcdb7498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requesteditems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('q_issued', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_status', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requesteditems_item_id'), 'requesteditems', ['item_id'], unique=False)
    op.alter_column('addexistingitems', 'date_issued',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('additems', 'date_issued',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('issueditems', 'date_issued',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issueditems', 'date_issued',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('additems', 'date_issued',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('addexistingitems', 'date_issued',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_index(op.f('ix_requesteditems_item_id'), table_name='requesteditems')
    op.drop_table('requesteditems')
    # ### end Alembic commands ###
