"""with audit trail action_id is integer

Revision ID: 98beee705a96
Revises: 605bceefa250
Create Date: 2023-12-07 11:21:30.827734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98beee705a96'
down_revision = '605bceefa250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audittrail', schema=None) as batch_op:
        batch_op.alter_column('action_id',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audittrail', schema=None) as batch_op:
        batch_op.alter_column('action_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
