"""Initial migration

Revision ID: e064b5ecc124
Revises: b9f4e8e003c6
Create Date: 2023-11-08 15:21:10.248829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e064b5ecc124'
down_revision = 'b9f4e8e003c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_user_id')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_case_id'))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
